---
apiVersion: v1
kind: Service
metadata:
  name: clap-server
  namespace: clap-system
  labels:
    app.kubernetes.io/name: "clap-server"
    app.kubernetes.io/component: "deployment"
    app.kubernetes.io/managed-by: "Clap"
    clap.cana.io/app-type: "server"
spec:
  selector:
    app.kubernetes.io/name: "clap-server"
    app.kubernetes.io/component: "deployment"
    app.kubernetes.io/managed-by: "Clap"
    clap.cana.io/app-type: "server"
  type: ClusterIP
  ports:
    - name: client
      port: 8008
      targetPort: 8008

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clap-server
  namespace: clap-system
  labels:
    app.kubernetes.io/name: "clap-server"
    app.kubernetes.io/component: "deployment"
    app.kubernetes.io/managed-by: "Clap"
    clap.cana.io/app-type: "server"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "clap-server"
      app.kubernetes.io/component: "deployment"
      app.kubernetes.io/managed-by: "Clap"
      clap.cana.io/app-type: "server"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "clap-server"
        app.kubernetes.io/component: "deployment"
        app.kubernetes.io/managed-by: "Clap"
        clap.cana.io/app-type: "server"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - clap-server
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - deployment
                  - key: clap.cana.io/app-type
                    operator: In
                    values:
                      - server
              topologyKey: kubernetes.io/hostname
      containers:
        - name: clap-server
          image: dneht/clap-server:1.0.0
          resources:
            requests:
              memory: 1Gi
              cpu: 200m
            limits:
              memory: 8Gi
              cpu: 2
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
          imagePullPolicy: Always
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 2
  minReadySeconds: 60